### ISSUE TITLE
Can't share key

### ISSUE THREAD

**Issue by Kinqdos** [kormax/apple-home-key-reader#20]
Hey first of all, your project works great! Thank you for doing research. I noticed, that I can't share the key with others. Is it, cause its not Apple certifified? Or can I scan the QR-Code on multiple devices or just once?

**Comment by kormax** [comment]
Apple has not enabled sharing for Home Keys, and I assume that they are not planning on adding it, even though the protocol has full support for it.

We can only speculate on why that is so, but in my opinion, there could be 2 reasons for this:
1) In terms of UX: Apple didn't want to mix up "automatic" sharing which happens if you add someone to your Apple Home together with manual one.
2) Business reasons: Apple were afraid that someone could reverse engineer the protocol and build a royalty free reader. In this case, one would have been able to use sharing functionality as a means of issuing virtual access credentials, which would have enabled the use of Home Key in shared space settings (housing/offices/gyms). For such use cases Apple has an "Apple Access Program", and it's seemingly very expensive, requires recurring licensing payments to have access to, and thus very profitable for them.

**Comment by Kinqdos** [comment]
Thanks for the explanation, thought there were a sharing option, like shown in this article https://support.shopyalehome.com/how-do-i-share-a-home-key-to-my-assure-lock-2-plus-HkwulJET2

**Comment by kormax** [comment]
What you're referring to isn't actually sharing, as most people think about that as being able to share from a Wallet pass screen.

In that FAQ, they're just showing how to add other people to your home, which adds the key to their devices.

You won't see that screen if you've upgraded HomeKit architecture and don't have an activr home hub.

**Comment by Kinqdos** [comment]
Well then nothing left to say, except thank you for your replies and the effort you put into this project. Its absolutely awesome to create your own home keys!
